=== bungeni-org/bungeni-editor/BungeniEditor/branches/fd-ui-noa/BungeniEditorClient/src/xsd/toolbar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:element name="toolbar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="root"/>
      </xs:sequence>
      <xs:attribute name="doctype" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="actionGroup"/>
      </xs:sequence>
      <xs:attribute name="visible" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="actionGroup">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="title"/>
        <xs:element maxOccurs="unbounded" ref="blockAction"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="uimodel" use="required" type="xs:NCName"/>
      <xs:attribute name="visible" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="blockAction">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="title"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="action"/>
          <xs:element ref="subaction"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="condition" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="showChildren" type="xs:boolean"/>
      <xs:attribute name="target" use="required" type="xs:NCName"/>
      <xs:attribute name="tooltip"/>
      <xs:attribute name="visible" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="action">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="title"/>
        <xs:element maxOccurs="unbounded" ref="tooltip"/>
      </xs:sequence>
      <xs:attribute name="condition" use="required" type="xs:anyURI"/>
      <xs:attribute name="mode" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="target" use="required"/>
      <xs:attribute name="visible" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="subaction">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="title"/>
        <xs:element maxOccurs="unbounded" ref="tooltip"/>
      </xs:sequence>
      <xs:attribute name="condition" use="required" type="xs:anyURI"/>
      <xs:attribute name="mode" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="target" use="required"/>
      <xs:attribute name="tooltip"/>
      <xs:attribute name="visible" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tooltip">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bungeni-org/bungeni-editor/BungeniEditor/branches/metadata-rework-may-2012/BungeniEditorClient/runtime_required/settings/configs/actions/toolbar_actions/debaterecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Action configuration for debate-records

HTML is allowed in tooltip texts :
<a>, <b>, <i>, <br />, <center>, <ul>, <li>, <u>

NOTE : DO NOT REFORMAT THIS FILE OR CHANGE INDENTATION GLOBALLY

-->
<toolbar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../../src/xsd/toolbar.xsd"
 doctype="debaterecord">
    <root visible="true">
        <actionGroup name="tabFavourites"
            visible="true"
            uimodel="wrap">
            <title xml:lang="eng">generic</title>
            <title xml:lang="spa">genérico</title>
            <blockAction name="Speeches"
                target="null"
                visible="true"
                condition="none">
                <title xml:lang="eng">speech</title>
                <title xml:lang="fra">FR-Speech</title>
                <title xml:lang="spa">discurso</title>
                <action name="PersonalStatement.create"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_personal_statement"
                    visible="true"
                    condition="textSelected:true :and:
                                !cursorInSection:speech[0-9]* :and:
                                cursorInSection:debaterecord">
                    <title xml:lang="eng">personal statement</title>
                    <title xml:lang="spa">declaración personal</title>
                    
                    <tooltip xml:lang="eng">
                        Personal Statement
                    </tooltip>
                </action>

                <action name="Heading.PersonalStatement"
                    
                    mode="TEXT_SELECTED_INSERT"
                    target="markup_communication_heading:heading_pstatement"
                    visible="true"
                    condition="cursorInSection:pstatemnt[0-9]* :and:
                                textSelected:true">
                    <title xml:lang="eng">··→ heading</title>
                    <title xml:lang="spa">··→ titulo</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selected text as Heading
                    </tooltip>
                </action>
                <action name="MinStatement.create"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_ministerial_statement"
                    visible="true"
                    condition="textSelected:true :and:
                                !cursorInSection:speech[0-9]* :and:
                                cursorInSection:debaterecord">
                    <title xml:lang="eng">ministerial statement</title>
                    <title xml:lang="spa">declaración ministerial</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selected text as Ministerial Statement
                    </tooltip>
                </action>
                <action name="Heading.MinStatement"
                    
                    mode="TEXT_SELECTED_INSERT"
                    target="markup_communication_heading:heading_mstatement"
                    visible="true"
                    condition="cursorInSection:mstatemnt[0-9]* :and:
                                textSelected:true">
                    <title xml:lang="eng">··→ heading</title>
                    <title xml:lang="spa">··→ titulo</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selected text as Heading
                    </tooltip>
                </action>
                <action name="speech.create"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_speech"
                    visible="true"
                    condition="textSelected:true :and:
                                !cursorInSection:speech[0-9]*">
                    <title xml:lang="eng">speech section</title>
                    <title xml:lang="spa">discurso de la sección</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selection as a Speech
                    </tooltip>
                </action>

                 <action name="Speech.listitem"
                    mode="TEXT_SELECTED_INSERT"
                    target="make_speech_block_section"
                    visible="true"
                    condition="textSelected:true :and:
                                cursorInSection:speech[0-9]*,spbody[0-9]*">
                    <title xml:lang="eng">··→ list-item</title>
                    <title xml:lang="spa">··→ list-item</title>
                     
                    <tooltip xml:lang="eng">
                        Identify the selected text as an item in a list
                    </tooltip>
                </action>

                <action name="Speech.SpeechBy"
                    mode="TEXT_SELECTED_INSERT"
                    target="speech_by"
                    visible="true"
                    condition="textSelected:true :and:
                                cursorInSection:speech[0-9]*">
                    <title xml:lang="eng">··→ by</title>
                    <title xml:lang="spa">··→ por</title>
                    
                    <tooltip xml:lang="eng">
                        Identify selected text as speech author's name
                    </tooltip>
                </action>

                <action name="Speech.SpeechBody"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_speech_body"
                    visible="true"
                    condition="textSelected:true :and:
                               cursorInSection:speech[0-9]* :and:
                               !sectionHasChild:spbody[0-9]*">
                    <title xml:lang="eng">··→ body</title>
                    <title xml:lang="spa">··→ cuerpo</title>
                    
                    <tooltip xml:lang="eng">
                        Select and mark speech body
                    </tooltip>
                </action>

<!-- (rm, feb 2012) - removed...
                <action name="Speech.Edit"
                    mode="TEXT_EDIT"
                    target="edit_speech"
                    visible="true"
                    condition="textSelected:true :and:
                               cursorInSection:speech[0-9]* :and:
                               !sectionHasChild:spbody[0-9]*">
                    <title xml:lang="eng">EDIT</title>
                    <tooltip xml:lang="eng">
                        Edit ...
                    </tooltip>
                </action>
-->



                <!-- markup a list item number in a speech, these action target names need to rationalized -->
                <action name="MarkupQuestionNo"
                    mode="TEXT_SELECTED_INSERT"
                    target="markup_question_no"
                    visible="true"
                    condition="textSelected:true :and:
                    cursorInSection:spbody[0-9]*">
                    <title xml:lang="eng">··→ item num</title>
                    <title xml:lang="spa">··→ punto principale</title>
                    
                    <tooltip xml:lang="eng">
                        Item Number
                    </tooltip>
                </action>

            </blockAction>
            <blockAction name="Communication"
                    target="null"
                    visible="true"
                    condition="none">
                <title xml:lang="eng">communication</title>
                <title xml:lang="spa">comunicación</title>
                
                <action name="Communication.fromTheChair"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_communication_section"
                    visible="true"
                    condition="cursorInSection:debaterecord :and:
                              textSelected:true">
                    <title xml:lang="eng">communication from the chair</title>
                    <title xml:lang="spa">comunicación del presidente</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selection as communication from the chair
                    </tooltip>
                </action>
                <action name="Heading.Communication.fromTheChair"
                    mode="TEXT_SELECTED_INSERT"
                    target="markup_communication_heading:heading_comchair"
                    visible="true"
                    condition="cursorInSection:comnctn[0-9]* :and:
                                textSelected:true">
                    <title xml:lang="eng">··→ heading</title>
                    <title xml:lang="spa">··→ titulo</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selection as Heading
                    </tooltip>
                </action>
                <action name="Communication.pointOfOrder"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_point_of_order"
                    visible="true"
                    condition="cursorInSection:debaterecord :and:
                                textSelected:true">
                    <title xml:lang="eng">point of order</title>
                    <title xml:lang="spa">cuestión de orden</title>
                    
                    <tooltip xml:lang="eng">
                        Mark selection as Point of Order
                    </tooltip>
                </action>
                <action name="Heading.Communication.pointOfOrder"
                    mode="TEXT_SELECTED_INSERT"
                    target="create_point_of_order_heading:heading_pointoforder"
                    visible="true"
                    condition="cursorInSection:porder[0-9]* :and:
                                textSelected:true">
